### ISSUE TITLE
Rework NMR instrument manufacturer

### ISSUE THREAD

**Issue by NRayya** [nmrML/nmrCV#12]
- [x] Import [OBI:manufacturer](https://terminology.nfdi4chem.de/ts/ontologies/obi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0000835&obsoletes=false)
- [x] Move [NMR instrument manufacturer](https://terminology.nfdi4chem.de/ts/ontologies/nmrcv/terms?iri=http%3A%2F%2FnmrML.org%2FnmrCV%23NMR%3A1400255&obsoletes=false) under [OBI:manufacturer](https://terminology.nfdi4chem.de/ts/ontologies/obi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0000835&obsoletes=false) and rename to 'NMR device manufacturer'
- [x] def NMR device manufacturer:  A manufacturer that produces NMR instruments and/or their parts.
- [x]  optional - we decided not to do it 
  - make ‘NMR instrument manufacturer’ subclass
  - make ‘NMR accessory / consumables manufacturer’ a sibling
  - make ‘historic NMR instrument manufacturer’ subclass
- [x] make the children all instances (named individuals) instead of classes
  - Some of the latter could then also be asserted to be the same as their OBI equivalents .Bruker is already present as instance in OBI
- [x] The manufacturers that will be kept in nmrCV are:
  - Agilent Technologies
  - Bruker
  - Doty Scientific
  - JEOL
  - JS Research
  - Kimble Chase
  - MR Resources
  - Oxford Instruments
  - Spinlock SRL
  - Tecmag
  - Varian
  - Wilmad
  - Magritek
  - Nanalysis
  - ThermoFisher
  - NMR Service
  - Deutero
  - Norell
  - Shigemi
  - Chemagnetics
  - Nalorac

We decided that for the time being, we will consider both manufacturers of whole spectrometers and parts as "device manufactures".

- [x] use [OBI:device](https://terminology.nfdi4chem.de/ts/ontologies/obi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0000968), which already contains subclasses for parts of NMR instruments (console, magnet) and [OBI:NMR instrument](https://terminology.nfdi4chem.de/ts/ontologies/obi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0000566) under measurement device, 
    - hence, move NMR spectrometers under 'OBI:measurement device' and its parts defined in nmrCV under the respective 'OBI:device' class
    - provide a mapping between nmrCV devices and already existing OBI NMR devices in SSSOM format
- [x] Link the devices parents (e.g., [Bruker NMR instrument](https://terminology.nfdi4chem.de/ts/ontologies/obi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0000596) to the corresponding manufactureres)

**Comment by NRayya** [comment]
We decided that for the time being, we will consider both manufacturers of whole spectrometers and parts as "device manufactures".
better to use [OBI:device](https://terminology.nfdi4chem.de/ts/ontologies/obi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0000968), which already contains subclasses for parts of NMR instruments (console, magnet) and [OBI:NMR instrument](https://terminology.nfdi4chem.de/ts/ontologies/obi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0000566) under measurement device

**Comment by NRayya** [comment]
> @NRayya should I interpret your last comment that part of resolving this issue is not just reusing [OBI:manufacturer](https://terminology.nfdi4chem.de/ts/ontologies/obi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0000835&obsoletes=false) and subsume the above listed NMR related ones under there, but also to do the same for the instruments and instrument parts under [OBI:device](https://terminology.nfdi4chem.de/ts/ontologies/obi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0000968) and [OBI:NMR instrument](https://terminology.nfdi4chem.de/ts/ontologies/obi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0000566) repsectively? If yes, we should add this to the description of the issue.

Done

**Comment by StroemPhi** [comment]
While working on the implementation in https://github.com/nmrML/nmrCV/tree/12-rework-NMR-instrument-manufacturer I noticed that we have a class 'NMR instrument vendor' which is defined as an 'instrument attribute' (basically a piece of information) that seems redundant to me, since we already have 'NMR device manufacturer'. Can we deprecate this as part of this issue?

**Comment by StroemPhi** [comment]
Working on subsuming existing NMR devices under the respective [OBI:device](https://terminology.nfdi4chem.de/ts/ontologies/obi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0000968) branch entails having to deprecate nmrCV classes that were already defined in OBI (coming originally from the nmrCV crew i.e. Daniel Schober). Now, in the current nmrCV some of these NMR devices are grouped under [NMRCV:cardinal part of NMR instrument](https://terminology.nfdi4chem.de/ts/ontologies/nmrcv/terms?iri=http%3A%2F%2FnmrML.org%2FnmrCV%23NMR%3A1400011), but as this class is being dropped when the OBI equivalents are used instead, its semantics gets lost. The solution would be to assert on its children in OBI that they are part of an [OBI:NMR instrument](https://terminology.nfdi4chem.de/ts/ontologies/obi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0000566) which is done in OBI only for [OBI:NMR sample tube](https://terminology.nfdi4chem.de/ts/ontologies/obi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0000578), [OBI:NMR probe](https://terminology.nfdi4chem.de/ts/ontologies/obi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0000516) and [OBI:magic angle spinning rotor](https://terminology.nfdi4chem.de/ts/ontologies/obi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0000523). I wil lmake these asserions for now in nmrCV, but since this is considered axiom injection, we will need to get this into OBI in a separate issue. So this is an interim fix, to get this issue resolved. When these axioms are requested by us in OBI we should also use this opporunity to revise the definitions of these classes, as they are not in line with the OBO Foundry best practices.

**Comment by NRayya** [comment]
> While working on the implementation in https://github.com/nmrML/nmrCV/tree/12-rework-NMR-instrument-manufacturer I noticed that we have a class 'NMR instrument vendor' which is defined as an 'instrument attribute' (basically a piece of information) that seems redundant to me, since we already have 'NMR device manufacturer'. Can we deprecate this as part of this issue?

We have now a separate issue for vendors: https://github.com/nmrML/nmrCV/issues/31

**Comment by NRayya** [comment]
> Working on subsuming existing NMR devices under the respective [OBI:device](https://terminology.nfdi4chem.de/ts/ontologies/obi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0000968) branch entails having to deprecate nmrCV classes that were already defined in OBI (coming originally from the nmrCV crew i.e. Daniel Schober). Now, in the current nmrCV some of these NMR devices are grouped under [NMRCV:cardinal part of NMR instrument](https://terminology.nfdi4chem.de/ts/ontologies/nmrcv/terms?iri=http%3A%2F%2FnmrML.org%2FnmrCV%23NMR%3A1400011), but as this class is being dropped when the OBI equivalents are used instead, its semantics gets lost. The solution would be to assert on its children in OBI that they are part of an [OBI:NMR instrument](https://terminology.nfdi4chem.de/ts/ontologies/obi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0000566) which is done in OBI only for [OBI:NMR sample tube](https://terminology.nfdi4chem.de/ts/ontologies/obi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0000578), [OBI:NMR probe](https://terminology.nfdi4chem.de/ts/ontologies/obi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0000516) and [OBI:magic angle spinning rotor](https://terminology.nfdi4chem.de/ts/ontologies/obi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0000523). I wil lmake these asserions for now in nmrCV, but since this is considered axiom injection, we will need to get this into OBI in a separate issue. So this is an interim fix, to get this issue resolved. When these axioms are requested by us in OBI we should also use this opporunity to revise the definitions of these classes, as they are not in line with the OBO Foundry best practices.

It was decided to do the fixes as needed in nmrCV and contact OBI team so that they import our terms and not the other way around as nmrCV is the NMR specific ontology. This will also solve the axiom injection

**Comment by StroemPhi** [comment]
To properly document the overlap with OBI, we need to provide a mapping between NMR devices defined in nmrCV and their equivalents in OBI as part of fixing this issue. We will provide this mapping in SSSOM format.
