### ISSUE TITLE
NMR solvent - Provide a definition 

### ISSUE THREAD

**Issue by NRayya** [nmrML/nmrCV#3]
We need a definition for the term [NMR solvent](https://terminology.nfdi4chem.de/ts/ontologies/nmrcv/terms?iri=http%3A%2F%2FnmrML.org%2FnmrCV%23NMR%3A1000330)

We will distinguish between the solvent itself and the solvent role. 

- [x] NMR solvent role: We will import definition from CHEBI: [“A solvent used in nuclear magnetic resonance (NMR) spectroscopy.”](https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_197449)
  - In CHEBI the role is called  "NMR solvent". We would like to rename to NMR solvent role
- [x] NMR solvent: "A molecular entity that is used as a solvent in nuclear magnetic resonance (NMR) spectroscopy."
  - No need to mention liquid state NMR as the solvent can be used in other rare cases.

**Comment by NRayya** [comment]
We will import definition from CHEBI: [“A solvent used in nuclear magnetic resonance (NMR) spectroscopy.”](https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_197449)

No need to mention liquid state NMR as the solvent can be used in other rare cases. This was discussed in the NMR task force meeting

**Comment by StroemPhi** [comment]
I propose the following, which I do in the [CHEBI import branch](https://github.com/nmrML/nmrCV/tree/Import-CHEBI-dependencies)

1. Import all molecular entities from CHEBI that are asserted to have an [NMR solvent](https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_197449) role --> done in 5e560edf7a3f251aaaf976877be923e589e6e5a3
2. Move [CHEBI:chemical entity](https://terminology.nfdi4chem.de/ts/ontologies/chebi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHEBI_24431) under [BFO:material entity](https://terminology.nfdi4chem.de/ts/ontologies/bfo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000040). It could also be subsumed under BFO:object, but this avoids the object/object aggregate distinction problem (see also: https://pubmed.ncbi.nlm.nih.gov/21533043) --> done in 530fd10fbcfffef07c7c62546dbdba931aac8a2f
3. Change the label of CHEBI:`NMR solvent` to `NMR solvent role` as it is defined as a role and not the material entity that bears this role --> done in 4c6f9bff707a55c41fc827706efc115007d9a733. Consider adding a comment which explains this label change.
4. Move [NMR solvent](https://terminology.nfdi4chem.de/ts/ontologies/nmrcv/terms?iri=http%3A%2F%2FnmrML.org%2FnmrCV%23NMR%3A1000330) under [CHEBI:molecular entity](https://terminology.nfdi4chem.de/ts/ontologies/chebi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHEBI_23367), because all NMR solvents are molecular entities, and add an equivalenceTo axiom that states that an NMR solvent is a molecular entity that bears the CHEBI:NMR solvent role. --> done in bd96327781098503fb6947b127f019edf1829861
5. Add the textual definition to NMR solvent: "A molecular entity that is used as a solvent in nuclear magnetic resonance (NMR) spectroscopy." --> done in 35d403ce778592fdcb79820e35b0c2a0f5d61657
6. Infer subclassOf NMR solvent axioms for those CHEBI molecular entities which bear a CHEBI:NMR solvent role using: `sh run.sh robot reason --reasoner ELK -i nmrcv-edit.owl --exclude-duplicate-axioms true --exclude-tautologies structural --annotate-inferred-axioms True convert -f ofn -o nmrcv-edit.owl`. This will be done automatically upon building the actual release files, but must be done manually, if we want to see this also in the edit file. --> done in dbde30f1d3f7b0a5808476389f0118d2157b5a36

**Comment by StroemPhi** [comment]
closed by #6
